### PR TITLE
Gregor - Added button styles q

### PR DESCRIPTION
**Pull request by uspsureshot**
Add some button classes

button 
button:hover 
button:active 
.btnFlat - 2 dimensional button that inherits background color, inherits hover and active states
.btn3d - 3d square button with hover and active states
.btn3d-rnd - 3d Oval or round button (depending on width) with active and hover states

### CODE REVIEW

**Review by preetha5 — COMMENTED** [review]
1. Are these button styles going to be different than the ones Sherry is working on? If so maybe they might be better inside a _buttons.scss. No?

2. I was planning to add helper classes(float/clear) in _helper.scss. Check out project plan.So we might not need it here. You can leave it for now, until I push that file.

3. Is there a need to set 'height:auto' for certain grid classes?Just curious if you are seeing any problems.

**Comment by uspsureshot** [comment]
1. As the buttons. I thought i was on forms. Didn't knows Sherry was
working the buttons.

2 That is fine-I just needed it to break the form fields. If you change the
name, let me know.


3.the Height: Auto - don't need. After I removed the 15px Padding.


On May 26, 2017 6:39 PM, "preetha5" <notifications@github.com> wrote:

*@preetha5* commented on this pull request.

   1.

   Are these button styles going to be different than the ones Sherry is
   working on? If so maybe they might be better inside a _buttons.scss. No?
   2.

   I was planning to add helper classes(float/clear) in _helper.scss. Check
   out project plan.So we might not need it here. You can leave it for now,
   until I push that file.
   3.

   Is there a need to set 'height:auto' for certain grid classes?Just
   curious if you are seeing any problems.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/preetha5/fewd2_final/pull/7#pullrequestreview-40642410>,
or mute the thread

**Comment by preetha5** [comment]
I have added the basic helper classes into new helper class file. Can u use that ? Also added the fixes for fpreset and grid.scss. You might want to rebase and push again.

**Comment by preetha5** [comment]
Will be creating new pull request

**Pull request closed without merging**
